---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openunison-{{ .Release.Name }}
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: network
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: openunison-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{ if eq .Values.network.ingress_type "traefik" }}
  annotations:
    {{ if .Values.network.traefik.secure }} 
    traefik.ingress.kubernetes.io/service.serversscheme: https
    {{ end }}
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: openunison-sticky
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "none"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
  {{ end }}
spec:
  ports:
  {{ if or ( eq .Values.network.ingress_type "istio" ) ( eq .Values.network.ingress_type "traefik" ) }}
  - name: https-{{ .Release.Name }}
  {{ else }}
  - name: openunison-secure-{{ .Release.Name }}
  {{ end }}
    port: 443
    protocol: TCP
    targetPort: 8443
  {{ if or ( eq .Values.network.ingress_type "istio" ) ( eq .Values.network.ingress_type "traefik" ) }}
  - name: http-{{ .Release.Name }}
  {{ else }}
  - name: openunison-insecure-{{ .Release.Name }}
  {{ end }}
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    application: openunison-{{ .Release.Name }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: "{{ .Values.network.service_type | default "ClusterIP" }}"
status:
  loadBalancer: {}
