services:
  api_server_host: "k8sapi.apps.192.168.2.148.nip.io"
  issuer_url: https://ou.apps.192.168.2.119.nip.io/auth/idp/remotek8s
  enable_tokenrequest: true
  token_request_audience: api
  token_request_expiration_seconds: 600


cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "docker.local.tremolo.dev/repository/openunison/managementproxy"

certs:
  use_k8s_cm: false

trusted_certs:
  - name: idp
    pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhVENDQWxHZ0F3SUJBZ0lRVGZOWUM1b0Q5ODlnOTVvYUF2SU9pakFOQmdrcWhraUc5dzBCQVFzRkFEQVcKTVJRd0VnWURWUVFEREF0cGJuUmxjbTVoYkMxallUQWVGdzB5TURFd01qTXhPREUwTURkYUZ3MHlNVEF4TWpFeApPREUwTURkYU1DMHhHREFXQmdOVkJBb1REM1J5WlcxdmJHOXpaV04xY21sMGVURVJNQThHQTFVRUF4TUlaWGgwCkxXTmxjblF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3ZHVFpraE9FRml0Z2IKOEV0UmhkdGdyS1BFVjQ4Z0hqZ2luK01IeTNPR0V3M09JTTVqVXZxb0FzaUtzTU54d1B1NHNDR1F5cmlrU3kyLwoxWlFydmRVcC9kQmloV0xYcFY1WUNVR3BqLzZreXhxUEpqM2hFTG9CSzhZNEtidy93OXNXN2czSHFTWG83RnBtClFxQ0tONTM1Rzk2ZkVlVU1ML3lsbStYR1BtN0V2cWRXK2h5ZTBTMXhoTklibEVxSE9RbVArQldkTEtzZ05KRWgKbVNjWTVpdlJvaVZiUVBqRkhHeEhzTmg2d0VWMFdqajR4cm1ySWZ3cTRBaGRMbzB4Qjcvc0phVldFRFpWejIwQQpFeHVGc2lUemFVY3hBa09Sd3RZMmtHTWFGU0FHMTlZQVd6T0dRZWtqb1NNMmR3MTBKODZNd0liMWhpNk82Yy9ICjhBV1RVVXdCQWdNQkFBR2pnWnN3Z1pnd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMkExVHl0ZUFLSmtYQlNBajAwemJaVnRPRjU4dwpTQVlEVlIwUkJFRXdQNEljYjNVdVlYQndjeTR4T1RJdU1UWTRMakl1TVRFNUxtNXBjQzVwYjRJZmF6aHpaR0l1CllYQndjeTR4T1RJdU1UWTRMakl1TVRFNUxtNXBjQzVwYnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXBBSVQKQnJMYkRmcVRrYkIyVDdSdW1aV0FuTUJhNEU2V1Q2T0tzVElsU09uUkxiRFRXL09ZRzJFWnFnbUxGUFNUb1NBYQpCemQxWTg5N2w4czBuS29mS3puT1AzaUJDSFJHL1ROTFBmdk5MSjc1ZGtOOSsyRnJWcHU1WnFzQ2RGZ0wvNC9PCk42ZlcvY3p3TEpianQzTnVLb2E4aCtaeHhHVkRFSVFjZjFnbDBUU3loVVVMeUFQSjJRNXpDelZrTFdFT2lXK2gKZHJZOHlEcUFZUkgxV0dYM3BwenV6SWVzMjhTaWRlaTVoLzltK3kwZEJEMmtCcGViWi8wa0RWRmQ0YTBpQjJ6Vgo5TmlZWDNIdTF5R0JteitLczF1WU5mdFlqc204a3NLZmJMUnlDSlBaZnhGbzIybDR1dXF4YkVKVUtoZnNTU1lLCnhDWmx2djRVdTZ2RjlJNWc4Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s


       